### ISSUE TITLE
Galacticraft...

### ISSUE THREAD

**Issue by therealericbj** [GrimCo/CoopLife2#66] opened 2020-04-09 02:59 UTC
Using the GDLauncher, I created a new instance with Coop Life 2 1.0.8.

All 3 Galacticraft files are still in the pack.

**Comment by TheDarkPreacher** [comment] 2020-04-09 03:05
Did you update the pack or install a fresh instance?

**Comment by therealericbj** [comment] 2020-04-09 03:08
Fresh instance.  I do have the the other version in the same launcher.  I'm playing the 1.0.7 version on a server.


________________________________

**Comment by TheDarkPreacher** [comment] 2020-04-09 03:11
Using GDLauncher, I checked the install for 1.08 myself. Cannot reproduce.
Checked Twitch import ZIP, Galacticraft files not included.
Checked mod list, No Galacticraft or dependencies listed.

Check and make sure you didn't open the wrong instance for CL2.

**Comment by therealericbj** [comment] 2020-04-09 03:24
Checked for correct instance.  I even checked to see if my server settings were there, they were not.  Then I went as far as deleting the instance and reinstalled a new instance.  Same issue occurred.

Don't you just love these random bits of WTH?

________________________________

**Comment by TheDarkPreacher** [comment] 2020-04-09 03:33
Installed 1.08 through GDLauncher search, cannot reproduce.
Installed 1.08 through Twitch Import ZIP in GDLauncher, cannot reproduce
Checked mod lists, mod folders of installs, cannot reproduce.

Only suggestion I have it to go into your install and manually remove the Galacticraft mods, then probably report this as a bug to the GD devs.

Closed #66 Cannot reproduce.

**Comment by therealericbj** [comment] 2020-04-09 04:01
Just for information purposes, downloaded the 1.0.8 pack on the Twitch Launcher, no Galacticraft files...

Also, Thank you for trying to help me so quickly...

________________________________

**Comment by Vaygrim** [comment] 2020-04-09 04:10
It looks like it might potentially be a regional Curse Distribution Server issue. 2 members of our team cannot reproduce it, but I can. For the moment my suggestion is to manually erase both Galacticraft mods and MicDoodle Core... and move on. If that doesn't work for this, try a fresh install tomorrow morning. Servers should be synced by then.

**Comment by therealericbj** [comment] 2020-04-09 04:13
So maybe has something to do with the fact I'm in Canada?

**Comment by therealericbj** [comment] 2020-04-09 04:18
Just remembered another bit of weirdness I noticed while trying to troubleshoot.

It had the correct version of Forge that you said updated to...
...but it added the Galacticraft files back in for you.  o.0

**Comment by Vaygrim** [comment] 2020-04-09 04:22
Exactly the same for me, and I'm in Texas.
Guess 1 - It's an issue with some of the CurseForge Distribution servers in certain areas.
Guess 2 - (Put forward by TheDarkPreacher) GDLauncher itself is getting confused somehow when downloading the pack.

Only suggestion I've got is give it till tomorrow, see if it clears.

**Comment by Ranzer1255** [comment] 2020-04-09 05:38
I did some poking around with the issue and was able to recreate it under precise conditions... 

I believe the problem is a caching bug in GD Launcher itself. When deleting an instance in the GD Launcher, it deletes the appropriate instance folder.

`ie: <appdata>/Roaming/GDLauncher/instances/packs/GrimCosCoopLife2`

 however it does *not* delete the corresponding cache in the Temp folder.

`ie: <appdata>/Roaming/GDLauncher/instances/temp/GrimCosCoopLife2`

this folder retains some data, in my case, the Galaticraft jars and other ancillary data. when you recreate the instance using the same instance name `default: GrimCosCoopLife2` , GDLauncher references this temp file as well as the download from Curse causing it to import the GC mods despite them not being in the 1.0.8 version

My suggestion would be to
A) delete this temp file when deleting an instance or attempting a "clean" install
or
B) give every pack a Unique instance name at creation so that the old temp file is never referenced

**Comment by therealericbj** [comment] 2020-04-09 06:38
I followed your suggestion Mr. Ranzer.  I deleted all Temp folders that refer to Coop Life 2 in any way.

Then I downloaed the Zip file myself from CurseForge, and then Imported the Instance.

It worked perfectly...

What would GDLauncher need all these Temp folders for anyways?

I also must say "Thank you" to everyone for the amazing support.  Please other Tech Support people how to do this.

________________________________

**Comment by therealericbj** [comment] 2020-04-09 06:57
...and then the Universe being the harsh, cruel mistress she is, spawned me into the world at the top of one of those giant redwood trees in a Redwood forest.  :(

**Comment by FoxBotGames** [comment] 2020-04-09 07:34
Issue detected compliant to the launcher service, not the pack itself. Closing issue, report to launcher service.
Information found in this issue will be used as a "work around" for future packs. 
GrimCo found your poor spawn location to be rather comical, enjoy the pack :D

**Closed as completed by FoxBotGames** 2020-04-09 07:34 UTC
Labels: bug

**Comment by Ranzer1255** [comment] 2020-04-17 06:28
This issue has been resolved in an upcoming release to the GD launcher.
